#version 460 core

// 
#extension GL_GOOGLE_include_directive : require

//
#include "lib/native.glsl"
#include "lib/fresnel.glsl"
#include "lib/random.glsl"
#include "lib/sphere.glsl"
#include "lib/rasterizer.glsl"
#include "lib/reprojection.glsl"

//
layout (local_size_x = 32, local_size_y = 8, local_size_z = 1) in;

// 
void main() {
  const uvec2 gcoord = gl_GlobalInvocationID.xy;
  const vec2 tCoord = (vec2(gcoord) + 0.5f)/vec2(extent);
  const uint linearId = gcoord.x + extent.x * gcoord.y;
  const uint type = linearId / (extent.x * extent.y);
  const uint pixelId = linearId % (extent.x * extent.y);

  //
  PixelSurfaceInfoRef surface = getPixelSurface(pixelId);
  //if (surface.origin.x != 0.f || surface.origin.y != 0.f || surface.origin.z != 0.f) {
    //reproject3D(pixelId, type);
  //};
};
