#version 460 core

// 
#extension GL_GOOGLE_include_directive : require

//
#include "lib/native.glsl"
#include "lib/fresnel.glsl"
#include "lib/random.glsl"
#include "lib/sphere.glsl"

//
layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

// 
void main() {
  if (gl_GlobalInvocationID.x < 8u) {
    previousCounters[gl_GlobalInvocationID.x] = counters[gl_GlobalInvocationID.x];
    counters[gl_GlobalInvocationID.x] = 0u;
  };
};
